- README.md
- lib/application.ex
- mix.exs
- test/test_helper.exs
… is provided, bare consumers and producer need to be handled by the client.
> Bump to 3.0.0. AMQPX is no longer an application

- lib/consumer.ex
Non era gestito il crash dell'handler del consumer. Se crashava l'`handler module` i messaggi rimanevano unacked e la connessione rimaneva in uno stato inconsistente
> Handle consumer crashes 

- README.md
- config/config.exs
- config/test.exs
- lib/consumer.ex
- mix.exs
Passaggio da
```
queue_dead_letter: "test1_errored",
queue_dead_letter_exchange: "test1_errored_exchange"
```
a:
```
queue_options: [
.....
arguments: [
{"x-dead-letter-routing-key", :longstr, "test1_errored"},
{"x-dead-letter-exchange", :longstr, "test1_errored_exchange"}
]
]
```
> Support for queue options

- config/test.exs
- lib/helper.ex
- lib/producer.ex
- mix.exs
- test/amqpx/amqpx_test.exs
- test/support/producer/producer_3.ex
Allow the declaration of exchanges in producer config. Useful for tests.
```elixir
config :amqpx, :producer, %{
publish_timeout: 5_000,
publisher_confirms: false,
exchanges: [
%{
name: "test_exchange",
type: :topic,
opts: [durable: true]
}
]
}
```
> Allow exchanges declaration in producer config

- .drone.yml
- README.md
- config/config.exs
- mix.exs
- publish
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-4305 
Dato che al momento del deploy viene chiesta la versione su suite-py ho fatto in modo che la stessa versione venga utilizzata per la release su hex.pm.
Sembrava più complesso di quello che è...
Ditemi che ne pensate, magari possiamo applicarlo ad altre librerie sia già esistenti che in futuro...
> [PRIMA-4305]: Automatizzare pubblicazione librerie elixir

- README.md
Fix a few typos into README.md.
Moreover I added an explicit port, since for me it took a while to discover that it must be not be a string.
> ✏️  Fix typos and clarifies that port must be an int

- lib/amqp/gen/connection_manager.ex
Fix `Amqpx.Gen.ConnectionManager` trying to match against `{:ok, _}` when opening a connection. Also, the GenServer was sleeping for `backoff` seconds before responding, causing producer/consumer processes restarting in a very short time and shutting down the application.
> Fix error ConnectionManager broker connection error handling

- README.md
- config/test.exs
- lib/amqp/connection.ex
- lib/amqp/helper.ex
- mix.exs
- test/connection_test.exs
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-8108 
Use credentials_obfuscation to encrypt password before pushing it into `ConnectionManager` genserver's state.
Password obfuscation is enabled by default.
> [PRIMA-8108]: AMQPX genera log in chiaro

- .tool-versions
- config/test.exs
- lib/amqp/gen/producer.ex
- mix.exs
- test/gen_test.exs
With this PR it will be possible to setup many producers inside the same supervision tree.  
This could be useful in order to address scenarios where we need producers with different configurations (e.g. one producer using publish confirms and one not).  
The new .tool-versions file you see inside PR is added only to facilitate local development using [asdf version manager](https://asdf-vm.com/). The dumped versions of elixir and erlang are exactly the same used inside the base image of the Dockerfile.
> Add handling of multiple producers

- README.md
- config/test.exs
- lib/amqp/gen/consumer.ex
- test/gen_test.exs
- test/support/consumer/consumer_handle_rejection.ex
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-9846
This PR aims to add an optional callback that gets triggered whenever an handle_message callback (or a Basic.ack) fail and the redelivered option is set to true. I'm still pretty new to elixir/beam ecosystem and functional programming so please challenge my proposal in any way possible 😄.
> [PRIMA-9846]: Add handle message rejection optional callback

- lib/amqp/gen/consumer.ex
- mix.exs
- test/gen_test.exs
- test/support/consumer/consumer_handle_rejection.ex
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-9846
This PR includes:
- Small fix to change the return type of `handle_message_rejection` callback from `{:ok}` to `:ok`
- `handle_message_rejection` now also has the rejected message as input for better observability
> message pass through to rejection handler

- .drone.yml
- config/test.exs
- docker-compose.yml
- lib/amqp/gen/connection_manager.ex
- lib/amqp/gen/consumer.ex
- lib/amqp/gen/producer.ex
- mix.exs
- test/gen_test.exs
- test/support/consumer/consumer_connection_two.ex
- test/support/producer/producer_other_connection.ex
- test/test_helper.exs
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/CAB-4786
Add support for multiple connections by adding configuration options in the various Amqpx components. The new options are:
- `:name` in `ConnectionManager`
- `:connection_name` in `Producer` and `Consumer`
We decided to leave `Amqpx.Gen.ConnectionManager` as default for all these options, so this PR should not be a breaking change. The users of this library will be able to create multiple connection managers, multiple producers tied to different connections, and multiple consumers tied to different connections as well
> [CAB-4786]: Add support for multiple connections

- config/test.exs
- lib/amqp/gen/consumer.ex
- test/gen_test.exs
- test/support/consumer/consumer_no_requeue.ex
This PR adds a `requeue_on_reject` option to allow a `Amqpx.Gen.Consumer` to skip the default requeue mechanism that is hard-coded right now in the library.
If the option is not set or set to `true`, the behaviour remains the same as today.
If the option is set to `false`:
1. the `handle_message_rejection` callback will be called
2. `Basic.reject` will be called with `requeue: false`
Please note that this PR should close issue #56.
> Add requeue_on_reject configuration option

- entrypoint
- lib/amqp/helper.ex
- mix.exs
- test/helper_test.exs
Since rabbitMQ by default [sends messages in DLX with the original routing key](https://www.rabbitmq.com/dlx.html#routing), the default binding for the `*_errored` queue should be the same as the original queue.
Of course things could be very complex if the original queue has more than one exchange etc, but then a DLX may not be feasible at all 🤷🏻
```elixir
%{
exchanges: [
%{
name: "exchange_name",
routing_keys: ["example_key"],
type: :topic
}
],
opts: [
durable: true,
arguments: [
{"x-dead-letter-exchange", :longstr, "errors_exchange"}
]
],
queue: "queue_name"
}
```
**before:**
```
TO queue_name_errored
ROUTING KEY #
```
**after:**
```
TO queue_name_errored
ROUTING KEY example_key
```
> Default binding for DLX queues instead of wildcard

- lib/amqp/gen/consumer.ex
Hey! I was wondering if it is of any value having the full stacktrace when rescuing general errors while handling messages.
This way we could better understand when some uncaught error occurs (e.g. atm we have some generic "%MatchError" logged from the consumer, but with no other indication on where they happened.
Let me know if it could be ok! :pray:
> [change] print stacktrace when rescuing exceptions

- lib/amqp/gen/consumer.ex
- lib/amqp/gen/producer.ex
- test/gen_test.exs
Previously, the Amqpx producers and consumers did not handle shutdown gracefully, resulting in noisy log messages and a strange behavior when the supervisor attempted to shut them down.
To address this issue and to support use cases where the actors need to be shut down gracefully, I have added a new `terminate` function to the actors implementation. It gracefully shuts down the associated channels when reasons like `:normal`, `:shutdown`, and `{:shutdown, reason :: term()}` are encountered. 
This change also enables the use of the library in distributed environments, where the actors may need to be shut down deliberately, such as when balancing nodes in a cluster.
> [STAFF-31] Add proper shutdown handling to Amqpx generic producers and consumers

- README.md
- lib/amqp/gen/consumer.ex
- lib/amqp/gen/producer.ex
- mix.exs
By using `:trap_exit` for handling shutdowns in consumers and producers, exit messages are received from any linked processes shutting down. Since the catch-all `handle_info` logs all messages without distinction and treats them as warnings, I've added a clause to reduce unnecessary noise
> Avoid logging normal exits

- lib/amqp/gen/connection_manager.ex
The ConnectionManager module was implementing the GenServer behaviour, with a proper terminate/2 function but it wasn't trapping exits so the terminate wasn't being called (ever). Moreover, it was abrutly closing the connection with an exit/2 call instead of using the proper function.
> Fix connection manager

- test/basic_test.exs
The test was flaky because it was relying on a weird race condition moslty related to the order the processes shutdown when closing a channel; sometimes it failed with
```
1) test basic consume cancel exits the process when channel is closed (BasicTest)
test/basic_test.exs:95
match (=) failed
code:  assert {:normal, _} = catch_exit(Basic.cancel(meta[:chan], consumer_tag))
left:  {:normal, _}
right: {
:noproc,
{:gen_server, :call, [#PID<0.372.0>, {:call, {:"basic.cancel", "amq.ctag-7S2NmqLj18nRwk_-O_tQ1A", false}, :none, #PID<0.360.0>}, 70000]}
}
stacktrace:
test/basic_test.exs:103: (test)
```
This can be easily reproduced by simply adding a 
```
:timer.sleep(100)
```
after closing the channel
I'd argue that this test was useless anyway (I still don't understand what the test purpose was) …
> Remove (useless) flaky test

- .tool-versions
- lib/amqp/connection.ex
- lib/amqp/dns.ex
- test/connection_test.exs
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-2274
This PR modifies the connection behavior of `amqpx` when connecting to a RabbitMQ cluster or host:
- If the `host` field in the connection parameters or the RabbitMQ URL is an IP address, the library will establish a direct connection to that IP.
- If the `host` field in the connection parameters or the RabbitMQ URL is a DNS record, the library will resolve the associated `A` records and attempt to connect to the first available IP address.
> [PLATFORM-2274]: Investigate possible DNS caching issues on our rabbitmq libraries

- CHANGELOG.md
- lib/amqp/gen/consumer.ex
- lib/amqp/no_signal_handler.ex
- lib/amqp/signal_handler.ex
- mix.exs
- test/gen_test.exs
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/COART-181
More details on how to use in the app https://github.com/primait/peano/pull/2425
> [COART-181]: Check Gracefully termination in all our applications

- CHANGELOG.md
- README.md
- catalog-info.yaml
- lib/amqp/application.ex
- lib/amqp/helper.ex
- mix.exs
Since [amqpx 6.1.1](https://github.com/primait/amqpx/blob/6.1.1/lib/amqp/helper.ex#L184-L190)
applications that didn't use `Helper.consumers_supervisor_configuration/1`
had to manually start `Amqpx.SignalHandler` to avoid crashing
during the [handle_message](https://github.com/primait/amqpx/blob/dcf521f4ffe2de1b53c7770d06b60b562c2bcdbb/lib/amqp/gen/consumer.ex#L258).
This pr reverts that behavior by starting this process under a newly created
amqpx application
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DEVEX-2418
> [DEVEX-2418]: Helper is mandatory since 6.1.2
